INSERT INTO ROLE(ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE(ROLE) VALUES ('ROLE_PROFESSOR');
INSERT INTO ROLE(ROLE) VALUES ('ROLE_ALUNO');

INSERT INTO USUARIO(NOME, LOGIN, EMAIL, SENHA) VALUES ('Administrador', 'admin', 'admin@gmail.com', '$2a$10$RwFYEpGG03f3TPsRfWkqpepD9LFnnQW/IKvhm/mNNS.rIU2bexwFi');
INSERT INTO USUARIO_ROLE(USUARIO_ID, ROLE_ID) VALUES (1, 1);