-- Roles
INSERT INTO ROLE(ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO ROLE(ROLE) VALUES ('ROLE_PROFESSOR');
INSERT INTO ROLE(ROLE) VALUES ('ROLE_ALUNO');

-- Usuário Admin
INSERT INTO USUARIO(NOME, LOGIN, EMAIL, SENHA) VALUES ('Administrador', 'admin', 'admin@gmail.com', '$2a$10$RwFYEpGG03f3TPsRfWkqpepD9LFnnQW/IKvhm/mNNS.rIU2bexwFi');
INSERT INTO USUARIO_ROLE(USUARIO_ID, ROLE_ID) VALUES (1, 1);

-- Professor A - certificador
INSERT INTO USUARIO(NOME, LOGIN, EMAIL, SENHA) VALUES ('Professor A', 'profa', 'profa@gmail.com', '$2a$10$RwFYEpGG03f3TPsRfWkqpepD9LFnnQW/IKvhm/mNNS.rIU2bexwFi');
INSERT INTO USUARIO_ROLE(USUARIO_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO PROFESSOR(USUARIO_ID, CERTIFICADOR) VALUES (2, 1);

-- Professor B - não certificador
INSERT INTO USUARIO(NOME, LOGIN, EMAIL, SENHA) VALUES ('Professor B', 'profb', 'profb@gmail.com', '$2a$10$RwFYEpGG03f3TPsRfWkqpepD9LFnnQW/IKvhm/mNNS.rIU2bexwFi');
INSERT INTO USUARIO_ROLE(USUARIO_ID, ROLE_ID) VALUES (3, 2);
INSERT INTO PROFESSOR(USUARIO_ID, CERTIFICADOR) VALUES (3, 0);

-- Aluno X
INSERT INTO USUARIO(NOME, LOGIN, EMAIL, SENHA) VALUES ('Aluno X', 'alunox', 'alunox@gmail.com', '$2a$10$RwFYEpGG03f3TPsRfWkqpepD9LFnnQW/IKvhm/mNNS.rIU2bexwFi');
INSERT INTO USUARIO_ROLE(USUARIO_ID, ROLE_ID) VALUES (4, 3);
INSERT INTO ALUNO(USUARIO_ID) VALUES (4);

-- Aluno Y
INSERT INTO USUARIO(NOME, LOGIN, EMAIL, SENHA) VALUES ('Aluno Y', 'alunoy', 'alunoy@gmail.com', '$2a$10$RwFYEpGG03f3TPsRfWkqpepD9LFnnQW/IKvhm/mNNS.rIU2bexwFi');
INSERT INTO USUARIO_ROLE(USUARIO_ID, ROLE_ID) VALUES (5, 3);
INSERT INTO ALUNO(USUARIO_ID) VALUES (5);

-- Questões e itens
INSERT INTO QUESTAO(ENUNCIADO, MATERIA, PROFESSOR_ID, CERTIFICADA, NUMERO_ACESSOS) VALUES ('Questão 1 sobre Linguagens e Códigos', 'LINGUAGENS_CODIGOS', 1, null, 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (1, 'Item A', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (1, 'Item B', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (1, 'Item C', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (1, 'Item D', 1);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (1, 'Item E', 0);

INSERT INTO QUESTAO(ENUNCIADO, MATERIA, PROFESSOR_ID, CERTIFICADA, NUMERO_ACESSOS) VALUES ('Questão 2 sobre Linguagens e Códigos', 'LINGUAGENS_CODIGOS', 1, null, 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (2, 'Item A', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (2, 'Item B', 1);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (2, 'Item C', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (2, 'Item D', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (2, 'Item E', 0);

INSERT INTO QUESTAO(ENUNCIADO, MATERIA, PROFESSOR_ID, CERTIFICADA, NUMERO_ACESSOS) VALUES ('Questão 1 sobre Ciências Humanas', 'CIENCIAS_HUMANAS', 1, null, 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (3, 'Item A', 1);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (3, 'Item B', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (3, 'Item C', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (3, 'Item D', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (3, 'Item E', 0);

INSERT INTO QUESTAO(ENUNCIADO, MATERIA, PROFESSOR_ID, CERTIFICADA, NUMERO_ACESSOS) VALUES ('Questão 2 sobre Ciências Humanas', 'CIENCIAS_HUMANAS', 1, null, 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (4, 'Item A', 1);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (4, 'Item B', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (4, 'Item C', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (4, 'Item D', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (4, 'Item E', 0);

INSERT INTO QUESTAO(ENUNCIADO, MATERIA, PROFESSOR_ID, CERTIFICADA, NUMERO_ACESSOS) VALUES ('Questão 1 sobre Ciências da Natureza', 'CIENCIAS_NATUREZA', 1, null, 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (5, 'Item A', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (5, 'Item B', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (5, 'Item C', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (5, 'Item D', 1);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (5, 'Item E', 0);

INSERT INTO QUESTAO(ENUNCIADO, MATERIA, PROFESSOR_ID, CERTIFICADA, NUMERO_ACESSOS) VALUES ('Questão 2 sobre Ciências da Natureza', 'CIENCIAS_NATUREZA', 1, null, 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (6, 'Item A', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (6, 'Item B', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (6, 'Item C', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (6, 'Item D', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (6, 'Item E', 1);

INSERT INTO QUESTAO(ENUNCIADO, MATERIA, PROFESSOR_ID, CERTIFICADA, NUMERO_ACESSOS) VALUES ('Questão 1 sobre Matemática', 'MATEMATICA', 2, null, 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (7, 'Item A', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (7, 'Item B', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (7, 'Item C', 1);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (7, 'Item D', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (7, 'Item E', 0);

INSERT INTO QUESTAO(ENUNCIADO, MATERIA, PROFESSOR_ID, CERTIFICADA, NUMERO_ACESSOS) VALUES ('Questão 2 sobre Matemática', 'MATEMATICA', 2, null, 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (8, 'Item A', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (8, 'Item B', 1);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (8, 'Item C', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (8, 'Item D', 0);
INSERT INTO ITEM_QUESTAO(QUESTAO_ID, TEXTO, CORRETO) VALUES (8, 'Item E', 0);

--Materiais
INSERT INTO MATERIAL(TITULO, DESCRICAO, NOME_ARQUIVO, MATERIA, PROFESSOR_ID, NUMERO_ACESSOS) VALUES ('Material 1 sobre Matemática', 'Material 1 sobre Matemática', 'nomeArquivo1.pdf', 'MATEMATICA', 2, 0);
INSERT INTO MATERIAL(TITULO, DESCRICAO, NOME_ARQUIVO, MATERIA, PROFESSOR_ID, NUMERO_ACESSOS) VALUES ('Material 2 sobre Ciências da Natureza', 'Material 2 sobre Ciências da Natureza', 'nomeArquivo2.pdf', 'CIENCIAS_NATUREZA', 2, 0);
INSERT INTO MATERIAL(TITULO, DESCRICAO, NOME_ARQUIVO, MATERIA, PROFESSOR_ID, NUMERO_ACESSOS) VALUES ('Material 3 sobre Ciências Humanas', 'Material 3 sobre Ciências Humanas', 'nomeArquivo3.pdf', 'CIENCIAS_HUMANAS', 2, 0);
INSERT INTO MATERIAL(TITULO, DESCRICAO, NOME_ARQUIVO, MATERIA, PROFESSOR_ID, NUMERO_ACESSOS) VALUES ('Material 4 sobre Linguagens e Códigos', 'Material 4 sobre Linguagens e Códigos', 'nomeArquivo4.pdf', 'LINGUAGENS_CODIGOS', 2, 0);