REM   Script: session_1
REM   Criação das tabelas de entidades

CREATE TABLE PESSOA( 
    PESSOA_ID INT PRIMARY KEY, 
    CPF INT NOT NULL UNIQUE, 
    NOME VARCHAR2(45), 
    EMAIL VARCHAR2(45) 
);

CREATE TABLE ALUNO( 
    ALUNO_ID INT PRIMARY KEY, 
    PESSOA_ID INT, 
    FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA 
);

CREATE TABLE PROFESSOR( 
    PROFESSOR_ID INT PRIMARY KEY, 
    PESSOA_ID INT, 
    FOREIGN KEY (PESSOA_ID) REFERENCES PESSOA, 
    CERTIFICADOR NUMBER(1), 
    CONSTRAINT CK_PROFESSOR_CERTIFICADOR CHECK (CERTIFICADOR IN (1,0)) -- 1 (TRUE) 2 (FALSE) 
);

CREATE TABLE MATERIA( 
    MATERIA_ID INT PRIMARY KEY, 
    NOME VARCHAR2(35) 
);

CREATE TABLE QUESTAO( 
    QUESTAO_ID INT PRIMARY KEY, 
    MATERIA_ID INT, 
    FOREIGN KEY (MATERIA_ID) REFERENCES MATERIA, 
    ENUNCIADO VARCHAR2(45), 
    CERTIFICADA NUMBER(1), 
    CONSTRAINT CK_QUESTAO_CERTIFICADA CHECK (CERTIFICADA IN (1,0)) -- 1 (TRUE) 2 (FALSE) 
);

CREATE TABLE ITEM( 
    ITEM_ID INT PRIMARY KEY, 
    QUESTAO_ID INT, 
    TEXTO VARCHAR2(45), 
    FOREIGN KEY (QUESTAO_ID) REFERENCES QUESTAO, 
    CORRETO NUMBER(1), 
    CONSTRAINT CK_ITEM_CORRETO CHECK (CORRETO IN (1,0)) -- 1 (TRUE) 2 (FALSE) 
);

CREATE TABLE MATERIAL( 
    MATERIAL_ID INT PRIMARY KEY, 
    MATERIA_ID INT, 
    FOREIGN KEY (MATERIA_ID) REFERENCES MATERIA, 
    PROFESSOR_ID INT, 
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR, 
    TITULO VARCHAR2(45) 
);

